services:
  web:
    build: .
    container_name: fastapi_web  # Cambiado de django_web a fastapi_web
    working_dir: /app
    # CAMBIO IMPORTANTE: comando para FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      # Asegúrate que esta ruta exista en tu PC. 
      # Si tu código está en la raíz, cámbialo por: - .:/app
      - .:/app 
      - ../project-frontend:/app/project-frontend
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  pg_data: